[project]
name = "simple-fastmcp-example"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["boto3","botocore","aioboto3","mcp","mcp-server","mcp-client","python-dotenv"]
