apiVersion: v1
kind: Secret
metadata:
  name: s3-server-secrets
type: Opaque
stringData: # Will be encoded automatically
  AWS_ACCESS_KEY_ID: "FhWNVKoWcTPxUm1VKVtO"
  AWS_SECRET_ACCESS_KEY: "jmtLdUBxt7gU8V1SmzwiU56AJS6D8wlbVID4v5K7"
