apiVersion: v1
kind: Service
metadata:
  name: s3-fastmcp-server
spec:
  selector:
    app: s3-fastmcp-server
  ports:
    - port: 80
      targetPort: 9999
      nodePort: 30999 # Choose port between 30000-32767
  type: NodePort
